### ISSUE TITLE
links inside tweets aren't preserved

### ISSUE THREAD

**Issue by amelling** [MatthewStanciu/twitter-og#2]
Long links that are included in a tweet are shortened to match the displayed URL text, causing the original link content to be lost.

[Original tweet](https://twitter.com/ducha_aiki/status/1676654509429235712?s=12&t=mlsC2deEPbG0qgieGoOKUw)
<img width="432" alt="Screenshot 2023-07-06 at 10 33 54 AM" src="https://github.com/MatthewStanciu/twitter-og/assets/1060341/808c7fbf-0c5b-4c95-afc8-0dc7ce602740">

[Twitter-og link](https://twitter-og.com/ducha_aiki/status/1676654509429235712?s=12&t=mlsC2deEPbG0qgieGoOKUw) in Slack
<img width="768" alt="Screenshot 2023-07-06 at 10 34 10 AM" src="https://github.com/MatthewStanciu/twitter-og/assets/1060341/68c203d9-bf1e-40fe-b5aa-d37ddb85f066">

**Comment by MatthewStanciu** [comment]
Oof, it seems like some longer URLs get truncated. Maybe this is part of the reason why Twitter changes them to short `t.co` links in the first place 🤔 

What's your opinion on the best path forward? Right now I'm thinking keep links as `t.co` if they're longer than the length at which they would be truncated & replace with the actual URLs if not.

**Comment by amelling** [comment]
That seems reasonable.
And thanks again for this project. It makes sharing much easier!

**Comment by yutakobayashidev** [comment]
It appears that each object in the `data.entities.urls` array contains the full URL in the `expanded_url` field.

Created pull request #3 

![screenshots 2023-11-16 20 58 57](https://github.com/MatthewStanciu/twitter-og/assets/91340399/790e3de8-efb0-414a-9e83-e5e38286a8d0)
